### ISSUE TITLE
Update team members' social media links

### ISSUE THREAD

**Issue by PoorCoderCreations** [SurPathHub/SurPathHub.github.io#103]
**Is your feature request related to a problem? Please describe.**
Some links for social media accounts of the team isn't working. This should be disabled or updated with the links. e.g. facebook profile link and twitter profile link

**Describe the solution you'd like**
ask the team members to git push with the updated code of their social media profiles

**Describe alternatives you've considered**
Don't show the button if for example they don't have twitter or instagram

**Additional context**
Just a concern.

**Comment by vinzvinci** [comment]
Closing this as we are preparing for the new design.
