### ISSUE TITLE
[FEATURE] Add logos for their respective socials

### ISSUE THREAD

**Issue by Panquesito7** [SurPathHub/SurPathHub.github.io#107]
**Is your feature request related to a problem? Please describe.**

It would look better if we add logos for their respective socials in the footer.
For example, the GitHub link should have its logo on the left, the same for the other ones.

**Describe the solution you'd like**

Add logos to the left for their respective socials (example explained above).

**Describe alternatives you've considered**

None.

**Comment by lavakush07** [comment]
I would love to work upon this issue.

**Comment by Panquesito7** [comment]
Feel free to work on it! 😄

**Comment by vinzvinci** [comment]
Closing this as we are preparing for the new design.
