### ISSUE TITLE
[BUG] Card on `Join Us` section is hidden under yellow circle

### ISSUE THREAD

**Issue by vikasganiga05** [SurPathHub/SurPathHub.github.io#110]
### Description of the bug

The bottom left part of the  card on [Join Us](https://surpathhub.org/#join) is hidden under yellow circle.

### Please add screenshots (if applicable)

![image](https://user-images.githubusercontent.com/74750414/148565148-05d3f3e9-3499-4fcf-a864-6a17e91f041f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Simperfy** [comment]
What browser are you using? It's fine on my end.
![image](https://user-images.githubusercontent.com/28738855/148640125-efe585d8-0201-4e81-8f6e-38a7bf3a836c.png)

**Comment by vikasganiga05** [comment]
> What browser are you using? It's fine on my end. ![image](https://user-images.githubusercontent.com/28738855/148640125-efe585d8-0201-4e81-8f6e-38a7bf3a836c.png)

Oh! okay, I am using Firefox v95.0.2 browser.

**Comment by Wishy-S** [comment]
Cause of this issue may be lies in the implementation of the Gecko  for Firefox.
