### ISSUE TITLE
[FEATURE] Create Navbar and Hero section 

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/SurPathHub.github.io#112]
### Detailed description

> Hacktoberfest Task 1:

Create navigation bar and hero section like this
![image](https://user-images.githubusercontent.com/73097560/194712718-419249ff-b0fb-49ec-9d94-5b0271778e25.png)

### Context

It is important for us to rebrand xD

### Possible implementation

Check the design in Figma: https://www.figma.com/file/svMDNK4ZuKMfg3ItEyQmQU/Surpathhub-Rebranding%5BREFERENCE%5D

### Additional information

**Please use these tech stacks:**
TailwindCSS and ReactJS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sutirthverma** [comment]
Hi, the figma file is not opening.

**Comment by vinzvinci** [comment]
Wait. Can you send view link @Tiansing

**Comment by mkubdev** [comment]
Hey can i work on this? 😄

**Comment by Tiansing** [comment]
Hey @vinzvinci and @mkubdev, I just updated the figma file, you all can now access the rebranding design through this link : 
**https://www.figma.com/file/svMDNK4ZuKMfg3ItEyQmQU/Surpathhub-Rebranding%5BREFERENCE%5D**

**Comment by sutirthverma** [comment]
I would love to work on this, can you assign it to me?

**Comment by vinzvinci** [comment]
Thanks @Tiansing. Assigned @sutirthverma :heavy_check_mark:

**Comment by vinzvinci** [comment]
I think you can create by using the current languages we used here, let us handle transferring the code to tailwind and react. Feel free to create PR

**Comment by sutirthverma** [comment]
ok, thanks

**Comment by sutirthverma** [comment]
Hey, do I have to keep the navbar fixed at top?

**Comment by Tiansing** [comment]
> Hey, do I have to keep the navbar fixed at top?

Hey @sutirthverma, yes that would be fine if you keep the navbar fixed at the top.

**Comment by Tiansing** [comment]
@sutirthverma any update on this?

**Comment by sutirthverma** [comment]
> @sutirthverma any update on this?

Almost finished, just working on some bugs.

**Comment by Tiansing** [comment]
> > @sutirthverma any update on this?
> 
> Almost finished, just working on some bugs.

That's great, keep going buddy!

**Comment by vinzvinci** [comment]
You can keep the old one. 

#125 coming up soon

**Comment by sutirthverma** [comment]
ok

**Comment by vinzvinci** [comment]
Sure! We are also in a hurry, kubdev migrating to nextjs #127
