### ISSUE TITLE
[FEATURE] Create the section of "Support our Program? "

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/SurPathHub.github.io#113]
### Detailed description

> Hacktoberfest Task 4

Start creating this section 

![image](https://user-images.githubusercontent.com/73097560/194712936-17a23f3f-993f-403a-a5d5-bdf3857b70b4.png)

### Context

This is very useful for the community program

### Possible implementation

Check the design in Figma: https://www.figma.com/file/svMDNK4ZuKMfg3ItEyQmQU/Surpathhub-Rebranding%5BREFERENCE%5D

### Additional information

**Please use these tech stacks:**
TailwindCSS and ReactJS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amitroy-thedev** [comment]
can i use plain css/scss for for the project ?
If yes then please assign me this project..
Thank you

**Comment by vinzvinci** [comment]
Sure! You can do that if it's fit to global layout.

**Comment by amitroy-thedev** [comment]
Hey @vinzvinci to use tailwindcss can i use cdn of it in index.html..

**Comment by vinzvinci** [comment]
> Hey @vinzvinci to use tailwindcss can i use cdn of it in index.html..

I think you can create by using the current languages we used here, let us handle transferring the code to tailwind and react. Feel free to create PR

**Comment by amitroy-thedev** [comment]
okay

**Comment by amitroy-thedev** [comment]
Hey @vinzvinci how to find the platinum, gold and silver icons ?
Give any solution

**Comment by vinzvinci** [comment]
Can you send the files @Tiansing

**Comment by amitroy-thedev** [comment]
Which files ?

**Comment by vinzvinci** [comment]
These what I mean, let me know if these works!

Silver
![silver](https://user-images.githubusercontent.com/73097560/194744538-84c7095e-82da-4997-b8b4-c1b449e997bf.png)

Gold
![gold1](https://user-images.githubusercontent.com/73097560/194744541-1cc89030-bee9-463e-8a37-8d72a4cbfb99.png)

Platinum
![platinum](https://user-images.githubusercontent.com/73097560/194744542-5a0b6e80-9861-4936-aee3-f659f12ed4ff.png)

**Comment by amitroy-thedev** [comment]
Hey @vinzvinci please provide the icon so that i can continue with the project..
The project is almost done.

**Comment by amitroy-thedev** [comment]
Do i need to set the background color and card color same as it is shown ?

**Comment by vinzvinci** [comment]
> Hey @vinzvinci please provide the icon so that i can continue with the project.. The project is almost done.

I don't have the orig icons, sorry. Maybe u can use other icon related to silver, gold, platinum for now

**Comment by amitroy-thedev** [comment]
Sorry that reply was before you sent the icons

**Comment by amitroy-thedev** [comment]
The project is done can i commit

**Comment by vinzvinci** [comment]
> The project is done can i commit

Yeah sure.

**Comment by amitroy-thedev** [comment]
I've pull request the code please review it..
