### ISSUE TITLE
[FEATURE] Create the section of "Why be part of SurPath Hub? "

### ISSUE THREAD

**Issue by Tiansing** [SurPathHub/SurPathHub.github.io#114]
### Detailed description

>Hacktoberfest Task 2:

Create the section of "Why be part of SurPath Hub?" section like this:
![image](https://user-images.githubusercontent.com/59194525/194713063-fedea9a5-2508-428c-aeb0-4a48621cd78a.png)

### Context

This is essential for our rebranding!

### Possible implementation

Check the design in Figma: https://www.figma.com/file/svMDNK4ZuKMfg3ItEyQmQU/Surpathhub-Rebranding%5BREFERENCE%5D

### Additional information

**Please use these tech stacks:**
_TailwindCSS and ReactJS_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bivas-Biswas** [comment]
Hey, can i work on this ??

**Comment by vinzvinci** [comment]
Sure @Bivas-Biswas! Assigned ✅

**Comment by Bivas-Biswas** [comment]
I have some queries,
- I can't access the Figma file.
- The description said, "Please use these tech stacks: TailwindCSS and ReactJS". But there is no starting point because the current tech stack is HTML, CSS, and js.

**Comment by vinzvinci** [comment]
> I have some queries,
> 
> * I can't access the Figma file.
> * The description said, "Please use these tech stacks: TailwindCSS and ReactJS". But there is no starting point because the current tech stack is HTML, CSS, and js.

Please wait for #112 to be created, we will start it. 

Figma file owner @Tiansing, wait for him as well.

**Comment by Tiansing** [comment]
> I have some queries,
> 
> * I can't access the Figma file.
> * The description said, "Please use these tech stacks: TailwindCSS and ReactJS". But there is no starting point because the current tech stack is HTML, CSS, and js.

@Bivas-Biswas  I just updated the figma file, you can now access and view the rebranding design mentioned on this comment
https://github.com/SurPathHub/SurPathHub.github.io/issues/112#issuecomment-1272429609

**Comment by vinzvinci** [comment]
Btw, 

I think you can create by using the current languages we used here, let us handle transferring the code to tailwind and react. Feel free to create PR

**Comment by Tiansing** [comment]
@Bivas-Biswas any update on this?
