### ISSUE TITLE
[FEATURE] Create the section of "Join our Community Program"

### ISSUE THREAD

**Issue by Tiansing** [SurPathHub/SurPathHub.github.io#115]
### Detailed description

>Hacktoberfest Task 3:

Create the section of "Join our Community Program" like this:
![image](https://user-images.githubusercontent.com/59194525/194713268-44be3033-69dd-4e1f-a5d2-df7af91b111c.png)

### Context

This is essential for our rebranding!

### Possible implementation

Check the design in Figma: https://www.figma.com/file/svMDNK4ZuKMfg3ItEyQmQU/Surpathhub-Rebranding%5BREFERENCE%5D

### Additional information

**Please use these tech stacks:**
_TailwindCSS and ReactJS_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
Hey, can i work on this task? 🥇

**Comment by vinzvinci** [comment]
Assigned ✅ @mkubdev

**Comment by vinzvinci** [comment]
Btw,

I think you can create by using the current languages we used here, let us handle transferring the code to tailwind and react. Feel free to create PR

**Comment by mkubdev** [comment]
Wow, just opened the massive `index.html` 👀

**Comment by vinzvinci** [comment]
> Wow, just opened the massive `index.html` 👀 Will try to do something..

Yeah xD. Have fun!

**Comment by Tiansing** [comment]
Can't wait to see the progress of your work 😃 @mkubdev
