### ISSUE TITLE
[FEATURE] Create "Read our Community Blog" section

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/SurPathHub.github.io#116]
### Detailed description

> Hacktoberfest task 5

Create our community blog like this

![image](https://user-images.githubusercontent.com/73097560/194713186-43c657ae-2945-4a28-ab3f-b24fe457c648.png)

### Context

To share our community blog

### Possible implementation

Check the design in Figma: https://www.figma.com/file/svMDNK4ZuKMfg3ItEyQmQU/Surpathhub-Rebranding%5BREFERENCE%5D

**Please use these tech stacks:**
TailwindCSS and ReactJS

### Additional information

If you have time, you can connect our dev.to https://dev.to/SurPathHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by debopriyadey** [comment]
Hello @vinzvinci, You can assign it to me.

**Comment by vinzvinci** [comment]
Assigned @debopriyadey :heavy_check_mark:
