### ISSUE TITLE
[FEATURE] Create Footer Section

### ISSUE THREAD

**Issue by Tiansing** [SurPathHub/SurPathHub.github.io#117]
### Detailed description

>Hacktoberfest Task 6:

Create Footer Section like this:
![image](https://user-images.githubusercontent.com/59194525/194713459-2c993ab4-9b4e-41fb-8a15-e9a419dff98f.png)

### Context

This is essential for our rebranding!

### Possible implementation

Check the design in Figma: https://www.figma.com/file/svMDNK4ZuKMfg3ItEyQmQU/Surpathhub-Rebranding%5BREFERENCE%5D

### Additional information

**Please use these tech stacks:**
_TailwindCSS and ReactJS_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amitroy-thedev** [comment]
Hey @Tiansing assign me this project..

**Comment by Urmilasc** [comment]
Hello , I want to contribute So can you please assign this to me ?

**Comment by vinzvinci** [comment]
Assigned ✅

**Comment by vinzvinci** [comment]
Btw,

I think you can create by using the current languages we used here, let us handle transferring the code to tailwind and react. Feel free to create PR

**Comment by vinzvinci** [comment]
Any update on this?

**Comment by Tiansing** [comment]
Is there any progress of your work @Urmilasc ??

**Comment by vinzvinci** [comment]
Closing this later if no response

**Comment by vinzvinci** [comment]
Continue in #127
