### ISSUE TITLE
Update Read me

### ISSUE THREAD

**Issue by iqrafirdose** [SurPathHub/SurPathHub.github.io#119]
### Detailed description

Having a good read me helps to know about the project .I will  update the read me by adding images, screenshots and try to looks good.

### Context

Read me shows everything of the project. I will update the read me that can be understandable to everyone.

### Possible implementation

I will add images, screenshots  of the community .

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iqrafirdose** [comment]
can  you assign me? I will start working

**Comment by vinzvinci** [comment]
I'm wondering what will u put there, can I see in this issue first? I'll make sure to assign u here after that

**Comment by iqrafirdose** [comment]
Hey! I updated the read me  and I  created the pull request  #121 .

**Comment by iqrafirdose** [comment]
Hacktoberfest  labelled as Invalid. Why?

**Comment by vinzvinci** [comment]
> Hacktoberfest labelled as Invalid. Why?

It didn't follow our standards but I can remove it, let's put it on hold for now. We are rebranding the site, so I think it's better to create it when the landing page is done.

**Comment by vinzvinci** [comment]
Closing this. We will provide summary issue for the README soon [here](https://github.com/SurPathHub/SurPathHub.github.io/issues).
