### ISSUE TITLE
[BUG] Remove Join Us section

### ISSUE THREAD

**Issue by Tiansing** [SurPathHub/SurPathHub.github.io#122]
### Description of the bug

Remove Join Us section

### Please add screenshots (if applicable)

Remove Join Us section for website rebranding like this:
![2022-10-09 21_44_57-](https://user-images.githubusercontent.com/59194525/194762302-22f47337-0d39-47ad-8dfc-b284ab02642b.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vavy06** [comment]
Hi, I can do the task. Can you assign it to me?
