### ISSUE TITLE
[FEATURE] Migrating to Next.js

### ISSUE THREAD

**Issue by mkubdev** [SurPathHub/SurPathHub.github.io#125]
### Detailed description

Hi 👋🏻 

We should migrate this website to Next.js :
* Server-side Rendering (better perf)
* HMR (Hot Module replacment) : Very better developer experience
* Imroved SEO

### Context

This change seems important to me as working in plain html/css is not funny and can become hard to maintain as the tech stack evolve quickly.

### Possible implementation

Just migrate everything to a next.js project.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
Hey kub! 

I agree with you, I think we should migrate them to next.js :) I want to see more next.js projects in this server :) 

Do you want to take this issue?

**Comment by vinzvinci** [comment]
Assigned ✔️ Looking forward to this!

**Comment by vinzvinci** [comment]
You'll create draft PR for the nextjs migration right? I think we talk about this on discord xD, so many notifs on my side (I always forgot ^^)
