### ISSUE TITLE
[FEATURE] Create a workflow for pages

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/SurPathHub.github.io#133]
### Detailed description

The website is newly built by nextjs. Need to create a workflow in order to run it via GitHub pages

### Context

Reference 
https://github.com/WebXDAO/WebXDAO.github.io/blob/main/.github/workflows/deploy-node.yml

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkubdev** [comment]
Hello vinz. I can help for this issue !

**Comment by vinzvinci** [comment]
Assigned ✔️ @mkubdev
