### ISSUE TITLE
[FEATURE] Update the Join our Community section

### ISSUE THREAD

**Issue by mkubdev** [SurPathHub/SurPathHub.github.io#140]
### Detailed description

The Join ou community Program section has Lorem Ipsum. 👇
![image](https://user-images.githubusercontent.com/50140834/196705298-06daa95d-fe28-4f3f-9ee1-3dddeb9eae8e.png)

### Context

This changes come from the Figma migration to Next.js. But we need to update them.

### Possible implementation

Text needed for the both programs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ryjin210** [comment]
Hi! Could you assign me this issue? I would like to change the content this section has :))
