### ISSUE TITLE
[FEATURE] Update Support our Program section

### ISSUE THREAD

**Issue by mkubdev** [SurPathHub/SurPathHub.github.io#143]
### Detailed description

The **Support our Program** section is displaying mocked program 👇

![image](https://user-images.githubusercontent.com/50140834/196708362-823f1338-8b72-44d0-8281-20685ec69070.png)

We need to update them by adding official programs.

### Context

We should update the mocked content from the Figma/Next.js migration.

### Possible implementation

Update the [`<SupportOurProgram />`](https://github.com/SurPathHub/SurPathHub.github.io/blob/main/src/components/homepage/SupportOurProgram.js) component.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ryjin210** [comment]
Hi @mkubdev I would like to try and update this section, here's an outline of what I'll do. Its based from the Figma/Next.js migration template that @vinzvinci showed me. let me know if its alright, ill submit a PR right away :)) 
![image](https://user-images.githubusercontent.com/77573336/198893060-3a2d1e30-d71f-4040-9d75-b0bad11a5ba1.png)

**Comment by vinzvinci** [comment]
This looks good to me already 😸
