### ISSUE TITLE
Add community projects

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/SurPathHub.github.io#31]
To Do:
- [x] Add 2 more cards in the project section

Add this on the card with a screenshot & description of the project repo. `Note: Use specific repo. in the button link (per card)`
- [x] Add <a href="https://github.com/SurPathHub/starter-kit">Starter Kit</a>
- [x] Add <a href="https://github.com/SurPathHub/hacktoberfest-philippines">Hacktoberfest Philippines</a>
- [x] Add <a href="https://github.com/SurPathHub/github-profile-ph">GitHub Profile PH</a>
- [x] Add <a href="https://github.com/SurPathHub/showcase-your-project">Showcase Your Project</a>
- [x] Add <a href="https://github.com/SurPathHub/SurPathHub.github.io">Community Website</a>
- [x] Add <a href="https://github.com/SurPathHub/support">Support</a>
~~-~~
If you like to do this, please show some screenshots in your PR.

**Comment by SandeepKrSuman** [comment]
Hey @vinzvinci can you give an example as to how the screenshot of the repo should look like ? If you can provide just one screenshot as an example that would be very helpful.

**Comment by vinzvinci** [comment]
Example:
![image](https://user-images.githubusercontent.com/73097560/116818387-9ef4f180-ab9d-11eb-9f3b-3700266704b7.png)

**Comment by vinzvinci** [comment]
Additionally: Please rename the button into `View`

**Comment by vinzvinci** [comment]
Do you want to take this issue @SandeepKrSuman ?

**Comment by SandeepKrSuman** [comment]
Yes. Can I work on this?

**Comment by vinzvinci** [comment]
Yes, I'll assign this to you @SandeepKrSuman

**Comment by SandeepKrSuman** [comment]
Thanks I'm working on it now.
