### ISSUE TITLE
🎨 Footer and Main section have same background color no difference

### ISSUE THREAD

**Issue by vikasganiga05** [SurPathHub/SurPathHub.github.io#37]
**Describe the bug**
The main and footer section of the website has a white background, So it's hard to differentiate the footer section. The user may think it's the main section. My suggestion is to choose a primary color that has a footer background and change the text and icon color according to it.

**To Reproduce**
1. Go to https://surpathhub.github.io/
2. Scroll down to the bottom of the page
3. See an error

**Expected behavior**
My suggestion is to choose a primary color that has a footer background and change the text and icon color according to it.

**Screenshots**
![image](https://user-images.githubusercontent.com/74750414/116819827-75cd6480-ab8f-11eb-8df1-d6257acf7d5d.png)

**Working Environment**

Operating System (eg. Linux): Windows

Browser (eg. Chrome): Chrome

Device (eg. Laptop or Phone): Laptop

**Additional context**
> Here are some ideas that I have been come up with

![image](https://user-images.githubusercontent.com/74750414/116819925-10c63e80-ab90-11eb-909b-9a5d3b00a89d.png)

![image](https://user-images.githubusercontent.com/74750414/116819983-5a168e00-ab90-11eb-8e88-42780364865d.png)

**Comment by vinzvinci** [comment]
Yeah it's a real problem. I like the first image, wanna work with issue?

**Comment by vinzvinci** [comment]
Yeah that's real problem. I like the first image, wanna work with issue?

**Comment by vikasganiga05** [comment]
> Yeah that's real problem. I like the first image, wanna work with issue?

Yeah! sure. I like to work on this :slightly_smiling_face:

**Comment by vinzvinci** [comment]
Okay, thanks for helping :smile:

**Comment by Bryson69** [comment]
That's a really good idea @vikasganiga05. Thank you. The first colour looks awesome
