### ISSUE TITLE
(FEATURE) Redesign the home section

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/SurPathHub.github.io#42]
To Do:
- Remove this text: `Let's help discover the best more open source projects.`
- Better put our mission: `Our aim is to put every Filipino student aspiring developer into an open-source world regardless of their position in life and everyone will receive equal treatment.`
- I like to put embedded YouTube video on the right, let's remove that image.

![image](https://user-images.githubusercontent.com/73097560/117125978-c7166780-adcc-11eb-8af5-8f1fd18ebdc2.png)

**Comment by SandeepKrSuman** [comment]
Hey @vinzvinci , I would like to work on this. Also do let me know about the YouTube video which you want to embed.

**Comment by vinzvinci** [comment]
My YouTube video isn't done yet. You can put this for now https://youtu.be/1ehpgbb3XD0

**Comment by SandeepKrSuman** [comment]
Alright, I'm working on this.
