### ISSUE TITLE
Redesign Join Us Section

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/SurPathHub.github.io#48]
To Do:
- [ ] Maybe put the GitHub & Discord logo on the right card? with a good design
~~-~~
- [x] Remove ~~Get insights that help your developer skills grow.~~
- [x] Change it to **Get insights that help your development skills grow**
~~-~~
- [x] Remove ~~Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi!~~
- [x] Change it to **Join us and let's collaborate**

<br />

![image](https://user-images.githubusercontent.com/73097560/117776183-d9315380-b26d-11eb-9667-2bb361485157.png)

If you have a proposal for the design and better wording for the community, feel free to drop it here.

**Comment by goyal-Dushi** [comment]
Hey @vinzvinci, I would like to address the issue!

**Comment by vinzvinci** [comment]
Hey @goyal-Dushi, feel free, I'm excited to see your idea.
