### ISSUE TITLE
Responsive nav_logo is unable to appear

### ISSUE THREAD

**Issue by Tiansing** [SurPathHub/SurPathHub.github.io#54]
**nav_logo bug**
The responsive nav_logo "SurPath Hub" is unable to display when the minimum width size reaches 767 and below.

**To Reproduce**
1. Go to '[https://surpathhub.github.io/]'
2. Inspect elemets or F12
3. Click on 'Toggle device emulation' 
![image](https://user-images.githubusercontent.com/59194525/123503695-1cf9e400-d687-11eb-97f1-f0ec0f652895.png)

4. Edit the width to 767
![image](https://user-images.githubusercontent.com/59194525/123503704-2f741d80-d687-11eb-9889-2cded8270c9e.png)

5. See the 'SurPath Hub' unable to appear

**Expected behavior**
The 'SurPath Hub' nav_logo needs to appear at any screen size of a device

**Screenshots**
![image](https://user-images.githubusercontent.com/59194525/123503770-998cc280-d687-11eb-8579-41dbe86e4128.png)

**Working Environment**

Operating System : Windows 10

Browser : Microsoft Edge

Device : Laptop and Phone

**Comment by vinzvinci** [comment]
Do you want to take this issue?

**Comment by Tiansing** [comment]
> Do you want to take this issue?

Sure! why not.

**Comment by vinzvinci** [comment]
Hehehe salamats

**Comment by Tiansing** [comment]
I fixed the issue by changing the block value of display property of nav__logo rule to flex.

**Comment by vinzvinci** [comment]
Thank you <3
