### ISSUE TITLE
Add Christian Igbaras to Our Team section

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/SurPathHub.github.io#55]
Hey friend @Tiansing , add yourself next to my profile.

**Comment by Tiansing** [comment]
> Hey friend @Tiansing , add yourself next to my profile.

Ok @vinzvinci , thanks for consideration

**Comment by Tiansing** [comment]
My profile has been added next to your profile!

**Comment by vinzvinci** [comment]
I have request #59

**Comment by vinzvinci** [comment]
I will close this issue now. Thanks
