### ISSUE TITLE
misalignment and unapropriate occurence of bx selector

### ISSUE THREAD

**Issue by Tiansing** [SurPathHub/SurPathHub.github.io#56]
**bx bx-menu and bx bx-x bug issue**
There are little misalignment and unapropriate appearance of bx bx-menu and bx bx-x selector on header. The bug occured in between the width of 769 to 1023 . 

**To Reproduce**
1. Go to 'https://surpathhub.github.io/'
2. Inspect Element or press F12 on your keyboard
3. Click on 'Toggle device emulation'
![image](https://user-images.githubusercontent.com/59194525/123529660-128e2780-d725-11eb-8ba2-91dca3c1407b.png)
4. Change the width and calibrate it in between 769 to 1023
![image](https://user-images.githubusercontent.com/59194525/123529695-77e21880-d725-11eb-8f3f-9ac32bb6998a.png)
5. See the bug
![image](https://user-images.githubusercontent.com/59194525/123529721-acee6b00-d725-11eb-9234-f2aa59ff8f76.png)

**Expected behavior**
The bx bx-menu and bx bx-x bug should be in an appropriate position and occur in specific position when the screen has been resized.

**Working Environment**

Browser (eg. Chrome): Microsoft Edge

**Comment by vinzvinci** [comment]
Would you like to take this issue?

**Comment by Tiansing** [comment]
> Would you like to take this issue?

Sure bro!

**Comment by vinzvinci** [comment]
#57 fixed
