### ISSUE TITLE
Add moderators to "Our Team" section

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/SurPathHub.github.io#58]
Add @xyrelljoi & @Assh12Dhayanna

**Comment by xyrelljoi** [comment]
Ok, I added my profile and created a PR already

**Comment by vinzvinci** [comment]
@xyrelljoi merged. Now waiting for @Assh12Dhayanna

**Comment by vinzvinci** [comment]
@NeekoNeeko add yourself as moderator.
