### ISSUE TITLE
Change our mission description

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/SurPathHub.github.io#67]
**Here's the new description:**

Our aim is to put every Filipino student, career shifter, or aspiring developer into an open-source world regardless of their position in life and everyone will receive equal treatment.

**Comment by rynrsts** [comment]
I do not know if this will sound better:

Our aim is to place every Filipino student, career shifter, or aspiring developer into an open-source environment regardless of their position in life, receiving equal treatment.

**Comment by xyrelljoi** [comment]
How about:

> To place every Filipino student, Career shifter, or Aspiring developer into an Open-Source environment and receive equal treatment regardless of their status

**Comment by deephunt3r** [comment]
> **Here's the new description:**
> 
> Our aim is to put every Filipino student, career shifter, or aspiring developer into an open-source world regardless of their position in life and everyone will receive equal treatment.

@vinzvinci okay! can I create a pr by changing home descriptiom

**Comment by vinzvinci** [comment]
**Final**
Our aim is to put every Filipino student, career shifter, or aspiring developer into an open-source environment regardless of their position in life and everyone will receive equal treatment.

Yeah go @deephunt3r, please be careful, only change the description. Thank you!
