### ISSUE TITLE
feat: Update our logo

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/SurPathHub.github.io#69]
We're using our old logo on this website. 

**Task:**
- Update our logo on the navbar using the image below
- Update our favicon using the image below 

![logo](https://user-images.githubusercontent.com/73097560/125588693-65330f95-ed48-46df-952b-78d768b0e956.png)

**Comment by xyrelljoi** [comment]
Can I be assigned in this issue?

**Comment by vinzvinci** [comment]
Yeah, you can start working with this issue now.
