### ISSUE TITLE
nav__menu is not closing when nav__links was clicked

### ISSUE THREAD

**Issue by Tiansing** [SurPathHub/SurPathHub.github.io#77]
nav__menu is not closing when nav__links was clicked

**Expected behavior**
nav__menu should be closed when nav__links was clicked

**Screenshots**
![image](https://user-images.githubusercontent.com/59194525/127663244-2f0fb533-c802-461f-b0fa-d75634add1e1.png)

**Comment by rynrsts** [comment]
If no one is doing this, I would like to.

**Comment by vinzvinci** [comment]
Feel free @rynrsts.
