### ISSUE TITLE
nav-btn arragement bug on 768px width

### ISSUE THREAD

**Issue by Tiansing** [SurPathHub/SurPathHub.github.io#84]
disordered nav-btn arrangement and some nav-btn is not visible when it reaches the exact 768px width

**Expected behavior**
nav-btn should be aligned orderly by row and all nav-btn's are visible. 

**Screenshots**
![image](https://user-images.githubusercontent.com/59194525/128598786-7cdeef9d-7163-4394-8ec1-4ac90af70edd.png)

**Comment by vinzvinci** [comment]
Uhm yeah, this isn't looking good. Wanna work for it?

**Comment by Tiansing** [comment]
Sure vincent!

**Comment by vinzvinci** [comment]
Have u done this issue or not? 

Uhm maybe @Ryjin210 can take this issue?

**Comment by vinzvinci** [comment]
Closing this as we are preparing for the new design.
