### ISSUE TITLE
Add more SurPath Hub team

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/SurPathHub.github.io#85]
We need to redesign the Team section and add other core members

**Comment by varunwho** [comment]
> We need to redesign the Team section and add other core members

Do you want the other members to be on the same page?

**Comment by vinzvinci** [comment]
Yep, only core members are on the same page. I'll gather their GitHub first.

**Comment by vinzvinci** [comment]
Administrator - https://github.com/Ryjin210
Operations Manager - https://github.com/huenique
Moderator  - https://github.com/chraem

**Comment by varunwho** [comment]
Ohk so I only need to add these 3 people right?

**Comment by vinzvinci** [comment]
Yes ✨

**Comment by varunwho** [comment]
![Screenshot 2021-08-22 144007](https://user-images.githubusercontent.com/53107832/130349441-9d75b208-b392-4873-8e4b-f4c0509e847b.png)

I've added their names & position, if you could send links of linkedin & other accounts, I'll add that too and the photo as well

**Comment by vinzvinci** [comment]
Their GitHub and Twitter are enough.

@Ryjin210
@huenique
@chraem 
> share your twitter links or linkedin

**Comment by Ryjin210** [comment]
https://twitter.com/Ryjinx210

**Comment by Ryjin210** [comment]
here is my linkedin account as well 
https://www.linkedin.com/in/mark-ryan-jancorda-6916a6204/

**Comment by vinzvinci** [comment]
Chraem Twitter: https://twitter.com/chraem2

**Comment by vinzvinci** [comment]
You can start working on this issue now, they can make their own PR later to add their social links. But please don't forget their GitHub profile link.
