### ISSUE TITLE
add GitHub & Dev Protocol logo to our website

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/SurPathHub.github.io#86]
Ex.

**Powered by**
- GitHub logo
- Dev Protocol logo

**Comment by pranxv** [comment]
If the issue is still open, I would like to work on it

**Comment by vinzvinci** [comment]
Yeah sure, thank you.

- https://devprotocol.xyz/
<img width="512" alt="Avatar w 01 (Twitter)" src="https://user-images.githubusercontent.com/73097560/130181401-80312b73-1642-4009-affc-e10daf976025.png">
