### ISSUE TITLE
Opacity issue in the team members section

### ISSUE THREAD

**Issue by varunwho** [SurPathHub/SurPathHub.github.io#88]
**Is your feature request related to a problem? Please describe.**
The opacity is too low in the team members section and the text is quite transparent

**Describe the solution you'd like**
To increase the opacity to 0.7-0.8 so that the text would be visible and also there would be a difference seen when we hover

![Screenshot 2021-08-22 130645](https://user-images.githubusercontent.com/53107832/130346719-2582b292-df71-4f57-a47f-30d0962e4631.png)

**Comment by vinzvinci** [comment]
Hmm, I don't see any problem here 🤔, but I like to hear the other team thoughts

**Comment by varunwho** [comment]
> Hmm, I don't see any problem here 🤔, but I like to hear the other team thoughts

Sure!
I was working with this same kinda card on another project and got suggestions to increase the opacity. Lemme know if you wanna change it

**Comment by vinzvinci** [comment]
May I see some example?

**Comment by MatteuSan** [comment]
Maybe default to normal opacity but when the user-container__wrap is hovered it will only focus the opacity on one user

**Comment by chraem** [comment]
> Maybe default to normal opacity but when the user-container__wrap is hovered it will only focus the opacity on one user

I agree with this but to make sure that we have the same thought I'll type what I understand.
- The containers opacity is 100%
- If one container is hovered, lower the opacity of other containers other than the one being hovered.

Are we on the same page?

**Comment by huenique** [comment]
Thought about this, too. From a typical visitor's point of view, it doesn't make sense to blend the profiles with the background, especially if the intention was to introduce certain individuals. You have to hover over each profile to get a clear enough image. If I didn't have a decent eyesight, I might not notice the transparent shapes immediately. I get the motivation behind the design choice, but it doesn't seem to quite work here and hence this issue, I guess.

**Comment by varunwho** [comment]
> May I see some example?

Opacity at 0.8
![normal](https://user-images.githubusercontent.com/53107832/130349313-03f9f40d-daaa-4437-b62c-366323ce6d74.png)

Opacity at 1 (when hovered)
![hover](https://user-images.githubusercontent.com/53107832/130349314-42e1c145-0a9b-4a99-a9ee-0f8599204195.png)

**Comment by vinzvinci** [comment]
Hmm okay, you're telling only text & social logos? not the background? if yeah, it's alright for me. You can make changes

**Comment by varunwho** [comment]
> Hmm okay, you're telling only text & social logos? not the background? if yeah, it's alright for me. You can make changes

Yeah the text, social logos and the photos

**Comment by vinzvinci** [comment]
Okay cool!
