### ISSUE TITLE
Powered by

### ISSUE THREAD

**Issue by rynrsts** [SurPathHub/SurPathHub.github.io#91]
**Is your feature request related to a problem? Please describe.**

"GitHub" and "Dev Protocol" are too dark that these would blend with the background. This would be bad in terms of readability, especially to those who have bad eyesight and are color blind. And since these contain links, it would hinder their purposes.

![image](https://user-images.githubusercontent.com/84888155/130351920-ada1fae1-0daf-4220-b369-67687eb5a5be.png)

<br>

**Describe the solution you'd like**

These are my suggestions:
 - Make the color lighter (light enough that it would contrast with the background),
 - Make the color gray (shade of gray used in the other texts in the footer), or
 - Just make it white

And if I were to add, it would be cool to place the logo first before the name (e.g. [GitHub's logo] GitHub). And also align GitHub's logo with its text.

**Comment by vinzvinci** [comment]
same issue: #90

**Comment by vinzvinci** [comment]
Would you like to work on this issue?

**Comment by rynrsts** [comment]
> same issue: #90

Ohh sorry, I did not notice. Should I close this?

**Comment by rynrsts** [comment]
> Would you like to work on this issue?

Alright!

**Comment by vinzvinci** [comment]
> > same issue: #90
> 
> Ohh sorry, I did not notice. Should I close this?

Nope, I'll close the other one.
