### ISSUE TITLE
Web vitals need improvements

### ISSUE THREAD

**Issue by devkurono** [SurPathHub/SurPathHub.github.io#95]
According to lighthouse your website performance is slow, check the link below for more information about your website performance: 
https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fsurpathhub.github.io%2F
![image](https://user-images.githubusercontent.com/68635840/132640157-35a7f1f9-4e3b-468c-9606-cb560d2a4fa0.png)

**Comment by vinzvinci** [comment]
Thanks for making this issue. Take a look at this issue @Tiansing and ask me if needed.

**Comment by heychrono** [comment]
Hello, I highly recommend, you guys, to use these:
1. Lazyload images - https://github.com/aFarkas/lazysizes
2. Image optimization - https://tinypng.com/

I hope it helps.

**Comment by Tiansing** [comment]
> Thanks for making this issue. Take a look at this issue @Tiansing and ask me if needed.

Ok great issue! I will work on this.

**Comment by Tiansing** [comment]
> Hello, I highly recommend, you guys, to use these:
> 
> 1. Lazyload images - https://github.com/aFarkas/lazysizes
> 2. Image optimization - https://tinypng.com/
> 
> I hope it helps.

I really appreciate your help. Thank you.

**Comment by heychrono** [comment]
Hello, any update on this issue?

**Comment by vinzvinci** [comment]
Hello @heychrono, we are busy preparing the Hacktoberfest Philippines event. Maybe you can take over this issue if ever you have some time?

Thank you for being active here.

**Comment by heychrono** [comment]
Great, I'll try to do it, if I get a free time, good luck on the event. 🥳

**Comment by vinzvinci** [comment]
Thank you!

**Comment by heychrono** [comment]
Hello @vinzvinci, can I adjust some designs here?

**Comment by vinzvinci** [comment]
Yes, feel free @heychrono.

**Comment by vinzvinci** [comment]
Closing this as we are preparing for the new design.
