### ISSUE TITLE
Change our logo

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/SurPathHub.github.io#97]
Hi @Tiansing can u change our logo? You can see it here https://github.com/SurPathHub/brand-assets

**Comment by Tiansing** [comment]
Ok I'll think for a better logo design for our community

**Comment by vinzvinci** [comment]
You can use this https://github.com/SurPathHub/brand-assets/blob/main/Resources/SurPath%20Hub%20Logos/SPH_transparent.png

**Comment by vinzvinci** [comment]
Or you can start to create our mascot logo

**Comment by Tiansing** [comment]
Ok I will accomplish that all together

**Comment by vinzvinci** [comment]
All good!
